on:
  push:
  workflow_dispatch: 

name: Unique cache key

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v4
        id: cache-restore
        with:
            key: ${{ runner.os }}-cache-${{ github.run_id }}
            path: cache
            restore-keys: |
              ${{ runner.os }}-cache-
      
      - run: mkdir -p cache
    
      - run: echo "${{ github.run_id }}" >> cache/file.txt
          
      - run: cat cache/file.txt | tee "$GITHUB_STEP_SUMMARY"

      - uses: actions/cache/save@v4
        if: always()
        with:
          path: cache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}